name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: libssh2-1-dev
      run: sudo  apt install libssh2-1-dev
    - name: boost
      run: sudo  apt install libboost-all-dev
    - name: make
      run: make
